---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no

  tasks:

  - name: Delete Cloudformation Stack
    cloudformation:
      stack_name: "{{ stack_name }}"
      state: "absent"
      region: "{{ region }}"
