---

- name: Add tower project
  tower_project:
    name: "openshift-ansible-contrib"
    description: "sync openshift-ansible-contrib"
    organization: "test"
    state: present
    tower_config_file: "~/tower_cli.cfg"


