- job_template: aws-infrastructure
  success_nodes:
  - inventory_source: aws (aws-inventory
    success_nodes:
    - job_template: aws-openshift-install
      success_nodes:
      - job_template: create_httpd_file
        success_nodes:
        - job_template: redhat-access-insights-client
